export const PATHS = [
  [
    ['UP', 'RW'],
    ['DW', 'DW'],
    ['RG', 'RG'],
    ['LF', 'LF'],
    ['RG', 'UP'],
    ['LF', 'LF'],
    ['LF', 'LF'],
    ['UP', 'UP'],
    ['RG', 'RG'],
  ],
  [
    ['UP', 'UP'],
    ['UP', 'UP'],
    ['LF', 'DW'],
    ['LF', 'LF'],
    ['LF', 'UP'],
    ['RG', 'RG'],
  ],
  [
    ['DW', 'DW'],
    ['UP', 'UP'],
    ['RG', 'RG'],
    ['UP', 'UP'],
    ['DW', 'UP'],
    ['LF', 'LF'],
    ['DW', 'DW'],
    ['UP', 'UP'],
    ['RG', 'LF'],
    ['RG', 'RG'],
  ],
  [
    ['UP', 'UP'],
    ['RG', 'RG'],
    ['UP', 'UP'],
  ],
  [
    ['LF', 'LF'],
    ['UP', 'LF'],
    ['UP', 'UP'],
    ['UP', 'UP'],
    ['LF', 'LF'],
    ['DW', 'DW'],
    ['UP', 'UP'],
    ['UP', 'UP'],
    ['UP', 'UP'],
    ['DW', 'DW'],
    ['UP', 'LF'],
    ['DW', 'DW'],
    ['UP', 'LF'],
    ['LF', 'LF'],
    ['RG', 'RG'],
    ['UP', 'UP'],
  ]
]